version: '2'
:
services:
  todo_list:
    build: ./
    image: todolist:latest
    container_name: todo_list
    restart: always
    environment:
      MYSQL_DSN: "root:root@tcp/todo_list?charset=utf8&parseTime=True&loc=Local"
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_list
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    container_name: redis
    image: redis:4.0.14
    restart: always
    command:
      --requirepass "fanone" #这一行是设置密码
    privileged: true

    volumes:
      - /usr/local/redis:/var/lib/redis
    ports:
      - 6379:6379